/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:2bce177b-25e6-475a-b5c3-1b7aa6419e96",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_6VN1yP8Z5",
    "aws_user_pools_web_client_id": "1cio8td4ihms5h76ulbu2kc6id",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7zpthbwhsndzhooor767jfx4n4.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "orderlambda",
            "endpoint": "https://ci6ugm0k9j.execute-api.eu-west-2.amazonaws.com/temp",
            "region": "eu-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "amplifyagora5f702052c910472baeceff16def91d93181750-temp",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
